spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wrm
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  server:
    port: 8888
