spring:
  datasource:
    url: jdbc:mysql://prod-db:3306/wrm
    username: root
    password: prodroot
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  server:
    port: 8888
  logging:
    level:
      root: WARN
